FROM isaac_ros_dev-x86_64:latest

# eliminar repo problemático de yarn
RUN rm -f /etc/apt/sources.list.d/yarn.list || true

RUN apt update && apt install -y \
    ros-humble-gscam \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    v4l-utils \
 && rm -rf /var/lib/apt/lists/*